// <auto-generated />
using ForEveryone.Shop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForEveryone.Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForEveryone.Shop.Domain.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackBoost")
                        .HasColumnType("integer");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int>("DefenseBoost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HealToFull")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackBoost = 10,
                            Cost = 100,
                            DefenseBoost = 0,
                            Description = "Aumenta el Ataque +10 permanentemente.",
                            HealToFull = false,
                            Name = "🗡️ Espada de Hierro"
                        },
                        new
                        {
                            Id = 2,
                            AttackBoost = 0,
                            Cost = 150,
                            DefenseBoost = 10,
                            Description = "Aumenta la Defensa +10 permanentemente.",
                            HealToFull = false,
                            Name = "🛡️ Armadura de Cuero"
                        },
                        new
                        {
                            Id = 3,
                            AttackBoost = 0,
                            Cost = 50,
                            DefenseBoost = 0,
                            Description = "Restaura toda tu vida al instante.",
                            HealToFull = true,
                            Name = "🧪 Poción de Vida"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
