// <auto-generated />
using System;
using ForEveryone.Kingdom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForEveryone.Kingdom.Infrastructure.Migrations
{
    [DbContext(typeof(KingdomDbContext))]
    [Migration("20260916163739_AddArmySystem")]
    partial class AddArmySystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kingdoms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmySize")
                        .HasColumnType("integer");

                    b.Property<int>("CastleLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCollectedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("Kingdoms", b =>
                {
                    b.OwnsMany("ForEveryone.Kingdom.Domain.Building", "Buildings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("KingdomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("KingdomId");

                            b1.ToTable("KingdomBuildings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("KingdomId");
                        });

                    b.OwnsOne("ForEveryone.Kingdom.Domain.Resources", "Resources", b1 =>
                        {
                            b1.Property<Guid>("KingdomsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Food")
                                .HasColumnType("integer")
                                .HasColumnName("Food");

                            b1.Property<int>("Gold")
                                .HasColumnType("integer")
                                .HasColumnName("Gold");

                            b1.Property<int>("Stone")
                                .HasColumnType("integer")
                                .HasColumnName("Stone");

                            b1.Property<int>("Wood")
                                .HasColumnType("integer")
                                .HasColumnName("Wood");

                            b1.HasKey("KingdomsId");

                            b1.ToTable("Kingdoms");

                            b1.WithOwner()
                                .HasForeignKey("KingdomsId");
                        });

                    b.Navigation("Buildings");

                    b.Navigation("Resources")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
